- name: Ban IPs or networks on all servers
  hosts: all
  become: true
  vars:
    ban_list_raw: ""   # переменная придет из Survey
    ban_time: 3600     # переменная тоже может быть из Survey
  tasks:
    - name: Ensure banlist exists with desired timeout
      command: ipset create banlist hash:net timeout {{ ban_time }} -exist

    - name: Convert comma-separated string into list
      set_fact:
        ban_list: "{{ ban_list_raw.split(',') | map('trim') | list }}"

    - name: Add IPs or networks to banlist
      loop: "{{ ban_list }}"
      command: ipset add banlist {{ item }} timeout {{ ban_time }} -exist
