---
- name: Gather facts
  setup:

- name: Collect disk usage
  set_fact:
    disk_info: "{{ ansible_mounts }}"

- name: Compute thresholds
  set_fact:
    cpu_cores: "{{ ansible_facts.processor_vcpus | default(ansible_facts.processor_count|default(1)) }}"
    max_load: "{{ (health_max_load_per_core | float) * (ansible_facts.processor_vcpus | default(ansible_facts.processor_count|default(1))) | float }}"

- name: Build report
  set_fact:
    health_report:
      host: "{{ inventory_hostname }}"
      os: "{{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"
      uptime: "{{ ansible_facts.uptime_seconds | int }}"
      cpu_cores: "{{ cpu_cores }}"
      load1: "{{ ansible_loadavg['1'] }}"
      load_ok: "{{ ansible_loadavg['1'] | float <= max_load | bool }}"
      mem_mb_total: "{{ ansible_facts.memtotal_mb }}"
      mem_mb_free: "{{ ansible_facts.memfree_mb }}"
      mem_free_pct: "{{ (ansible_facts.memfree_mb / (ansible_facts.memtotal_mb|float)) * 100.0 }}"
      disks_raw: "{{ disk_info }}"
      time: "{{ ansible_date_time.iso8601 }}"

- name: Summarize and print
  debug:
    msg:
      - "Host: {{ health_report.host }} ({{ health_report.os }})"
      - "CPU cores: {{ health_report.cpu_cores }}, Load1: {{ health_report.load1 }} (<= {{ max_load | round(2) }} ok? {{ health_report.load_ok }})"
      - "Mem: {{ health_report.mem_mb_free }} / {{ health_report.mem_mb_total }} MB ({{ health_report.mem_free_pct | round(1) }}% free)"
      - "Disks:"
      - "{{ health_report.disks_raw }}"

- name: service facts
  service_facts:

- name: Report service states (ssh, cron)
  vars:
    critical_services:
      - ssh
      - cron
  debug:
    msg: >-
      {{
        critical_services | map('extract', ansible_facts.services) | list
      }}

- name: Post webhook with report
  uri:
    url: "{{ health_alert_webhook }}"
    method: POST
    status_code: 200,204
    body_format: json
    body: "{{ {'host': inventory_hostname, 'report': health_report} }}"
  when: health_alert_webhook | length > 0
  changed_when: false
