---
- name: Gather facts
  ansible.builtin.setup:


- name: Compute thresholds
  ansible.builtin.set_fact:
    node_health_cpu_cores: "{{ ansible_facts.processor_vcpus | default(ansible_facts.processor_count | default(1)) }}"
    node_health_max_load: >-
      {{ (health_max_load_per_core | float) *
         (ansible_facts.processor_vcpus | default(ansible_facts.processor_count | default(1))) | float }}

- name: Build report
  ansible.builtin.set_fact:
    node_health_report:
      host: "{{ inventory_hostname }}"
      os: "{{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"
      uptime: "{{ ansible_facts.uptime_seconds | int }}"
      cpu_cores: "{{ node_health_cpu_cores }}"
      load1: "{{ ansible_loadavg['1'] }}"
      load_ok: "{{ ansible_loadavg['1'] | float <= node_health_max_load | bool }}"
      mem_mb_total: "{{ ansible_facts.memtotal_mb }}"
      mem_mb_free: "{{ ansible_facts.memfree_mb }}"
      mem_free_pct: "{{ (ansible_facts.memfree_mb / (ansible_facts.memtotal_mb | float)) * 100.0 }}"
      mounts: "{{ ansible_mounts }}"
      time: "{{ ansible_date_time.iso8601 }}"

- name: Summarize and print
  ansible.builtin.debug:
    msg:
      - "Host: {{ node_health_report.host }} ({{ node_health_report.os }})"
      - >-
        CPU cores: {{ node_health_report.cpu_cores }}, Load1: {{ node_health_report.load1 }}
        (<= {{ node_health_max_load | round(2) }} ok? {{ node_health_report.load_ok }})
      - "Mem: {{ node_health_report.mem_mb_free }} / {{ node_health_report.mem_mb_total }} MB ({{ node_health_report.mem_free_pct | round(1) }}% free)"
      - "Mounts:"
      - "{{ node_health_report.mounts }}"

- name: Service facts
  ansible.builtin.service_facts:

- name: Report service states (ssh, cron)
  vars:
    critical_services:
      - ssh
      - cron
  ansible.builtin.debug:
    msg: >-
      {{
        critical_services | map('extract', ansible_facts.services) | list
      }}

- name: Post webhook with report
  ansible.builtin.uri:
    url: "{{ health_alert_webhook }}"
    method: POST
    status_code: 200,204
    body_format: json
    body: "{{ {'host': inventory_hostname, 'report': node_health_report} }}"
  when: health_alert_webhook | length > 0
  changed_when: false
