all:
  children:
    central:
      hosts:
        central-1:
          ansible_host: 10.0.0.10
    agents:
      hosts:
        agent-1:
          ansible_host: 10.0.0.11
        agent-2:
          ansible_host: 10.0.0.12
        agent-3:
          ansible_host: 10.0.0.13
