---
- name: Ban IP on all agents
  hosts: agents
  gather_facts: no
  vars:
    ban_ip: "{{ ip }}"
    ban_ttl: "{{ ttl | default(fw_ipset_timeout) }}"
  tasks:
    - name: Add IP to ipset with timeout
      command: "ipset add {{ fw_ipset_name }} {{ ban_ip }} timeout {{ ban_ttl }}"
      register: add_res
      failed_when: add_res.rc not in [0,1]
      changed_when: add_res.rc == 0
      become: true

    - name: Save current ipset to file
      shell: "ipset save > /etc/ipset.rules"
      become: true
      when: fw_persist_rules | default(true) | bool
