---
- name: Unban IP on all agents
  hosts: agents
  gather_facts: no
  vars:
    unban_ip: "{{ ip }}"
  tasks:
    - name: Delete IP from ipset (ignore if absent)
      command: "ipset del {{ fw_ipset_name }} {{ unban_ip }}"
      register: del_res
      failed_when: false
      changed_when: del_res.rc == 0
      become: true

    - name: Save current ipset to file
      shell: "ipset save > /etc/ipset.rules"
      become: true
      when: fw_persist_rules | default(true) | bool
