- name: Ban IP on all servers
  hosts: all
  become: true
  vars:
    # Keep vars aligned with sec_ipset_ban_list.yml for AWX Survey compatibility
    ban_list_raw: ""   # e.g. "1.2.3.4" or "1.2.3.4, 5.6.7.8"
    ban_time: 3600
  tasks:
    - name: Convert string to list
      set_fact:
        ban_list: "{{ ban_list_raw.split(',') | map('trim') | reject('equalto','') | list }}"

    - name: Add each IP to banlist
      loop: "{{ ban_list }}"
      loop_control:
        label: "{{ item }}"
      command: ipset add banlist {{ item }} timeout {{ ban_time }} -exist
