- name: Add IPs or networks to banlist
  hosts: all
  become: true
  vars:
    ban_list_raw: ""    # вводится через Survey: "1.2.3.4, 10.0.0.0/8"
    ban_time: 3600      # время в секундах (также через Survey)
  tasks:
    - name: Convert string to list
      set_fact:
        ban_list: "{{ ban_list_raw.split(',') | map('trim') | reject('equalto','') | list }}"

    - name: Add each IP or network to banlist
      loop: "{{ ban_list }}"
      loop_control:
        label: "{{ item }}"
      command: ipset add banlist {{ item }} timeout {{ ban_time }} -exist
